### ISSUE TITLE
odd behavior with "for loop"

### ISSUE THREAD

**Issue by goofyclown** [TheGreatSageEqualToHeaven/Fiu#4] opened 2023-08-02 14:07 UTC
using [Luau 0.588](https://github.com/Roblox/luau/releases/tag/0.588) with options "--binary -O2 -g0"

raw code:
```lua
for i,v in {`joe: {1+5}`, `word {string.rep("meow",2)}`} do
	print(v)
end
```
compiled bytecode:
[OUTPUT.txt](https://github.com/TheGreatSageEqualToHeaven/Fiu/files/12240852/OUTPUT.txt)

excepted output:
![image](https://github.com/TheGreatSageEqualToHeaven/Fiu/assets/42712457/f866d8ce-3125-45ff-a871-a22e3df47af6)

output given:
![image](https://github.com/TheGreatSageEqualToHeaven/Fiu/assets/42712457/0cc8b06d-ac3c-4721-bee5-e0608cdc9f78)
(prints 2 times "word meowmeow")

**Comment by TheGreatSageEqualToHeaven** [comment] 2023-08-02 21:41
Thanks for the repro case!

Do note that the current version of Fiu is in a pre-release state and isn't stable right now. I haven't had time recently to dedicate to the project to make a proper release. 

This is most likely caused by incorrect handling of generalized iteration rather than incorrect handling of generic for loops. I'll look into this issue when I have time

**Comment by TheGreatSageEqualToHeaven** [comment] 2024-01-06 18:42
Sorry for the late update, I'll get to fixing this in February.

**Comment by TheGreatSageEqualToHeaven** [comment] 2024-01-07 00:56
This is fixed in the latest commit.

**Closed by TheGreatSageEqualToHeaven** 2024-01-07 00:56 UTC
Labels: bug, good first issue
